### ISSUE TITLE
test checklist

### ISSUE THREAD

**Issue by kianzarrin** [kianzarrin/AdvancedRoads#6]
check list:
- [ ] load save test:  place AR segments -> change TMPE options and custom AR flags -> save -> load -> check if everything is rendered properly.

vanilla mode test - check if asset editor works in vanilla mode :
- [ ] hints are OK for the most part
- [ ] create vanilla road -> rename -> save -> load in asset editor -> check if it works
- [ ] create new road based on the road above -> save -> load -> check if it works
- [ ] test the roads above in game

AR mode test - check if asset editor works in AR mode :
- [ ] hints are OK for the most part
- [ ] create road with AR features -> rename -> save -> load in asset editor  -> check if it works
- [ ] create new road based on the road above -> rename -> save -> load -> check if it works
- [ ] check the roads above in game
